package cn.blogss.mapper;

import cn.blogss.pojo.Farm;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int insert(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int insertSelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    Farm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Farm record);

    //总记录数
    public abstract int totRecord(Farm slide);

    //农场查看,分页
    public abstract List<Farm> selectFarmByPage(@Param("pageIndex")int pageIndex,
                                                @Param("pageSize")int pageSize,
                                                @Param("farm")Farm farm);

    //删除一条
    void delOne(String id);

    //农场删除
    public abstract int delBatch(String[] ids);

    Farm editShow(String id);

    List<Farm> raiseAddShow();
}