package cn.blogss.mapper;

import cn.blogss.pojo.Link;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    Link selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Link record);

    public abstract List<Link> selectLinkByPage(@Param("pageIndex")int pageIndex,
                                                @Param("pageSize")int pageSize,
                                                @Param("link")Link link);

    //新闻分类批量删除
    public abstract void delBatch(String[] ids);

    public int totRecord(Link linkCat);
}