package cn.blogss.mapper;

import cn.blogss.pojo.NewsCat;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewsCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    int insert(NewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    int insertSelective(NewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    NewsCat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_cat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsCat record);

    //菜单查看,分页
    public abstract List<NewsCat> selectNewsCatByPage(@Param("pageIndex") int pageIndex, @Param("pageSize") int pageSize,
                                                @Param("newsCat") NewsCat newsCat);

    //菜单批量删除
    public abstract void delBatch(String[] ids);

    public int totRecord(NewsCat newsCat);
}