package cn.blogss.mapper;

import cn.blogss.pojo.RaiseCat;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RaiseCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    int insert(RaiseCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    int insertSelective(RaiseCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    RaiseCat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RaiseCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raise_cat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RaiseCat record);

    public abstract List<RaiseCat> selectRaiseCatByPage(@Param("pageIndex")int pageIndex,
                                                        @Param("pageSize")int pageSize,
                                                        @Param("raiseCat")RaiseCat raiseCat);

    //新闻分类批量删除
    public abstract void delBatch(String[] ids);

    //模糊查询总记录
    public int totRecord(RaiseCat raiseCat);

    //添加新闻时的查询
    public List<RaiseCat> raiseAddShow();

    void increaseNumByCatId(Integer catId);

    List<RaiseCat> selectRaiseCat();
}