package cn.blogss.mapper;

import cn.blogss.pojo.Users;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */

    Users getUsersByUsersName(String userName);

    List<String> queryPermissionsByUsersName(String userName);

    List<String> queryRolesByUsersName(String userName);

    int updateByPrimaryKey(Users record);

    public abstract List<Users> selectUsersByPage(@Param("pageIndex")int pageIndex,
                                                  @Param("pageSize")int pageSize,
                                                  @Param("users")Users users);

    //用户批量删除
    public abstract void delBatch(String[] ids);

    public int totRecord(Users users);

    public int queryUserByIDAndPwd(@Param("id") Integer id,@Param("password") String password);

    public int queryByEmail(String email);

    int queryByPhone(String phone);

    int updateEmailById(@Param("id") Integer id,@Param("email") String email);

    int updatePhoneById(@Param("id") Integer id,@Param("phone") String phone);

    int updatePwdById(@Param("id") Integer id,@Param("password") String password);

}