package cn.blogss.pojo;

import java.util.Date;

public class Visit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.userAgent
     *
     * @mbggenerated
     */
    private String useragent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.browserType
     *
     * @mbggenerated
     */
    private String browsertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.platformType
     *
     * @mbggenerated
     */
    private String platformtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.id
     *
     * @return the value of visit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.id
     *
     * @param id the value for visit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.ip
     *
     * @return the value of visit.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.ip
     *
     * @param ip the value for visit.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.userAgent
     *
     * @return the value of visit.userAgent
     *
     * @mbggenerated
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.userAgent
     *
     * @param useragent the value for visit.userAgent
     *
     * @mbggenerated
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent == null ? null : useragent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.city
     *
     * @return the value of visit.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.city
     *
     * @param city the value for visit.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.url
     *
     * @return the value of visit.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.url
     *
     * @param url the value for visit.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.browserType
     *
     * @return the value of visit.browserType
     *
     * @mbggenerated
     */
    public String getBrowsertype() {
        return browsertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.browserType
     *
     * @param browsertype the value for visit.browserType
     *
     * @mbggenerated
     */
    public void setBrowsertype(String browsertype) {
        this.browsertype = browsertype == null ? null : browsertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.platformType
     *
     * @return the value of visit.platformType
     *
     * @mbggenerated
     */
    public String getPlatformtype() {
        return platformtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.platformType
     *
     * @param platformtype the value for visit.platformType
     *
     * @mbggenerated
     */
    public void setPlatformtype(String platformtype) {
        this.platformtype = platformtype == null ? null : platformtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.time
     *
     * @return the value of visit.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.time
     *
     * @param time the value for visit.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    public Visit(){};

    public Visit(String browsertype,String platformtype){
        this.browsertype = browsertype;
        this.platformtype = platformtype;
    }
}